# Generated by Django 5.0.1 on 2024-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "userID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("auth0ID", models.CharField(max_length=45, unique=True)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("birthdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("gutt", "Gutt"),
                            ("jente", "Jente"),
                            ("ikke-binær", "Ikke-binær"),
                            ("vil ikke si", "Vil ikke si"),
                        ],
                        max_length=15,
                    ),
                ),
                ("days_without_incident", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=45, unique=True)),
                ("guardian_name", models.CharField(max_length=100)),
                ("guardian_phone", models.CharField(max_length=20)),
                ("verified", models.BooleanField(default=False)),
                ("banned", models.BooleanField(default=False)),
            ],
        ),
    ]
