# Generated by Django 5.0.1 on 2024-06-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "activityID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="activity_pics/placeholder-image.png",
                        null=True,
                        upload_to="activity_pics",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("limit", models.PositiveIntegerField(blank=True, null=True)),
                ("signed_up_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employeeID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("auth0ID", models.CharField(max_length=45, null=True)),
                ("employee_Name", models.CharField(max_length=100)),
                ("role", models.CharField(default="employee", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "levelID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=45)),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "userID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("auth0ID", models.CharField(max_length=45, unique=True)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("birthdate", models.DateField()),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="profile_pics/default_profile_picture.png",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("gutt", "Gutt"),
                            ("jente", "Jente"),
                            ("ikke-binær", "Ikke-binær"),
                            ("vil ikke si", "Vil ikke si"),
                        ],
                        max_length=15,
                    ),
                ),
                ("points", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=45, unique=True)),
                ("guardian_name", models.CharField(max_length=100, null=True)),
                ("guardian_phone", models.CharField(max_length=20, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("banned", models.BooleanField(default=False)),
                ("banned_from", models.DateField(blank=True, null=True)),
                ("banned_until", models.DateField(blank=True, null=True)),
                ("info", models.CharField(default="", max_length=1000, null=True)),
                ("role", models.CharField(default="member", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PollQuestion",
            fields=[
                (
                    "questionID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("question", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SuggestionBox",
            fields=[
                (
                    "suggestionID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=45, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "activityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.activity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.members",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberCertificate",
            fields=[
                ("certificateID", models.AutoField(primary_key=True, serialize=False)),
                ("certificate_image", models.ImageField(upload_to="certificates")),
                ("certificate_name", models.CharField(max_length=100, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.members",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivitySignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.activity",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.members",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="digital_medlemsordning.members",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="digital_medlemsordning.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollAnswer",
            fields=[
                (
                    "answerID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("answer", models.CharField(max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="digital_medlemsordning.pollquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.members",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.pollanswer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.pollquestion",
                    ),
                ),
            ],
        ),
    ]
