# Generated by Django 5.0.1 on 2024-06-19 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.DeleteModel(
            name="ActivityDate",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
