# Generated by Django 5.0.1 on 2024-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employeeID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("employee_Name", models.CharField(max_length=100)),
            ],
        ),
    ]
