# Generated by Django 5.0.1 on 2024-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0005_activitysignup"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
