# Generated by Django 5.0.1 on 2024-02-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0010_alter_members_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="banned_until",
            field=models.DateField(null=True),
        ),
    ]
