# Generated by Django 5.0.1 on 2024-03-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0011_members_banned_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="info",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="members",
            name="guardian_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="members",
            name="guardian_phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
