# Generated by Django 5.0.1 on 2024-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digital_medlemsordning",
            "0012_members_info_alter_members_guardian_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="info",
            field=models.CharField(default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="members",
            name="profile_pic",
            field=models.ImageField(
                default="digital_medlemsordning/files/profile_pics/default_profile_picture.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
