# Generated by Django 5.0.1 on 2024-03-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0015_alter_members_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="banned_from",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="members",
            name="banned_until",
            field=models.DateField(default=None),
        ),
    ]
