# Generated by Django 5.0.1 on 2024-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digital_medlemsordning",
            "0016_members_banned_from_alter_members_banned_until",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SugestionBox",
            fields=[
                (
                    "suggestionID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("suggestion", models.CharField(max_length=500)),
            ],
        ),
    ]
