# Generated by Django 5.0.1 on 2024-03-10 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0017_sugestionbox"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SugestionBox",
            new_name="SuggestionBox",
        ),
    ]
