# Generated by Django 5.0.1 on 2024-03-10 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0018_rename_sugestionbox_suggestionbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestionbox",
            name="suggestion",
        ),
    ]
