# Generated by Django 5.0.1 on 2024-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0019_remove_suggestionbox_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionbox",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="suggestionbox",
            name="title",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
