# Generated by Django 5.0.1 on 2024-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digital_medlemsordning",
            "0021_alter_members_banned_from_alter_members_banned_until",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="banned_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="members",
            name="banned_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
