# Generated by Django 5.0.1 on 2024-03-11 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0026_userlevel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLevel",
        ),
    ]
