# Generated by Django 5.0.1 on 2024-03-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0027_delete_userlevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "levelID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("naame", models.CharField(max_length=45)),
                ("points", models.IntegerField()),
            ],
        ),
    ]
