# Generated by Django 5.0.1 on 2024-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0028_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="naame",
            new_name="name",
        ),
    ]
