# Generated by Django 5.0.1 on 2024-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0029_rename_naame_level_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="role",
            field=models.CharField(default="member", max_length=20),
        ),
    ]
