# Generated by Django 5.0.1 on 2024-03-18 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_medlemsordning', '0030_employee_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='sign_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='digital_medlemsordning.members'),
        ),
    ]
