# Generated by Django 5.0.1 on 2024-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0030_members_role"),
        (
            "digital_medlemsordning",
            "0031_remove_employee_user_activity_sign_up_and_more",
        ),
    ]

    operations = []
