# Generated by Django 5.0.1 on 2024-03-19 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0033_pollquestion_pollanswer_questionnaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="chosen_answer",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionnaire",
            name="member",
        ),
        migrations.DeleteModel(
            name="PollAnswer",
        ),
        migrations.DeleteModel(
            name="PollQuestion",
        ),
        migrations.DeleteModel(
            name="Questionnaire",
        ),
    ]
