# Generated by Django 5.0.1 on 2024-03-19 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0035_pollquestion_pollanswer_questionnaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollanswer",
            old_name="answer",
            new_name="anwser",
        ),
    ]
