# Generated by Django 5.0.1 on 2024-03-19 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0036_rename_answer_pollanswer_anwser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnaire",
            old_name="chosen_answer",
            new_name="anwserID",
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="member",
            new_name="memberID",
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="question",
            new_name="questionID",
        ),
    ]
