# Generated by Django 5.0.1 on 2024-03-19 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "digital_medlemsordning",
            "0037_rename_chosen_answer_questionnaire_anwserid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollanswer",
            old_name="anwser",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="pollanswer",
            old_name="anwserID",
            new_name="answerID",
        ),
        migrations.RenameField(
            model_name="questionnaire",
            old_name="anwserID",
            new_name="answerID",
        ),
    ]
