# Generated by Django 5.0.1 on 2024-03-20 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0038_rename_anwser_pollanswer_answer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Questionnaire",
        ),
    ]
