# Generated by Django 5.0.1 on 2024-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0040_memberanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="auth0ID",
            field=models.CharField(default="default", max_length=45, unique=True),
        ),
    ]
