# Generated by Django 5.0.1 on 2024-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0041_employee_auth0id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(default="employee", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="auth0ID",
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
