# Generated by Django 5.0.1 on 2024-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0041_employee_auth0id_employee_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="sign_up",
        ),
    ]
