# Generated by Django 5.0.1 on 2024-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0042_remove_activity_sign_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
