# Generated by Django 5.0.1 on 2024-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0042_employee_role_alter_employee_auth0id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(max_length=20),
        ),
    ]
