# Generated by Django 5.0.1 on 2024-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0043_activity_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="signed_up_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
