# Generated by Django 5.0.1 on 2024-05-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0044_activity_limit_activity_signed_up_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCertificate",
            fields=[
                ("certificateID", models.AutoField(primary_key=True, serialize=False)),
                ("certificate_image", models.ImageField(upload_to="certificates")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_medlemsordning.members",
                    ),
                ),
            ],
        ),
    ]
