# Generated by Django 5.0.1 on 2024-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0045_membercertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="membercertificate",
            name="certificate_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
