# Generated by Django 5.0.1 on 2024-05-10 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digital_medlemsordning", "0046_membercertificate_certificate_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="certificate",
        ),
    ]
